//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspAppClient.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Admin", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class Admin : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdminEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdminGenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdminNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdminPasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdminPhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsMainAdminField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdminEmail {
            get {
                return this.AdminEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.AdminEmailField, value) != true)) {
                    this.AdminEmailField = value;
                    this.RaisePropertyChanged("AdminEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdminGender {
            get {
                return this.AdminGenderField;
            }
            set {
                if ((object.ReferenceEquals(this.AdminGenderField, value) != true)) {
                    this.AdminGenderField = value;
                    this.RaisePropertyChanged("AdminGender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdminName {
            get {
                return this.AdminNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AdminNameField, value) != true)) {
                    this.AdminNameField = value;
                    this.RaisePropertyChanged("AdminName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdminPassword {
            get {
                return this.AdminPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.AdminPasswordField, value) != true)) {
                    this.AdminPasswordField = value;
                    this.RaisePropertyChanged("AdminPassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdminPhone {
            get {
                return this.AdminPhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.AdminPhoneField, value) != true)) {
                    this.AdminPhoneField = value;
                    this.RaisePropertyChanged("AdminPhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsMainAdmin {
            get {
                return this.IsMainAdminField;
            }
            set {
                if ((this.IsMainAdminField.Equals(value) != true)) {
                    this.IsMainAdminField = value;
                    this.RaisePropertyChanged("IsMainAdmin");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPath", ReplyAction="http://tempuri.org/IService1/GetPathResponse")]
        string GetPath();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CheckAdminExist", ReplyAction="http://tempuri.org/IService1/CheckAdminExistResponse")]
        bool CheckAdminExist(string aEmail, string aPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddNewAdmin", ReplyAction="http://tempuri.org/IService1/AddNewAdminResponse")]
        int AddNewAdmin(string aName, string aEmail, string aPass, string aPhone, string aGender);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/IsMainAdmin", ReplyAction="http://tempuri.org/IService1/IsMainAdminResponse")]
        bool IsMainAdmin(string aEmail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAdminByEmail", ReplyAction="http://tempuri.org/IService1/GetAdminByEmailResponse")]
        AspAppClient.ServiceReference1.Admin GetAdminByEmail(string aEmail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateAdmin", ReplyAction="http://tempuri.org/IService1/UpdateAdminResponse")]
        int UpdateAdmin(AspAppClient.ServiceReference1.Admin a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddNewCategory", ReplyAction="http://tempuri.org/IService1/AddNewCategoryResponse")]
        int AddNewCategory(string catName, string catImage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/IsCategoryExist", ReplyAction="http://tempuri.org/IService1/IsCategoryExistResponse")]
        bool IsCategoryExist(string catName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddNewUser", ReplyAction="http://tempuri.org/IService1/AddNewUserResponse")]
        int AddNewUser(string uName, string uEmail, string uGender, string uBirthday, string uPass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CheckUserExist", ReplyAction="http://tempuri.org/IService1/CheckUserExistResponse")]
        bool CheckUserExist(string uEmail, string uPass);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : AspAppClient.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<AspAppClient.ServiceReference1.IService1>, AspAppClient.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetPath() {
            return base.Channel.GetPath();
        }
        
        public bool CheckAdminExist(string aEmail, string aPassword) {
            return base.Channel.CheckAdminExist(aEmail, aPassword);
        }
        
        public int AddNewAdmin(string aName, string aEmail, string aPass, string aPhone, string aGender) {
            return base.Channel.AddNewAdmin(aName, aEmail, aPass, aPhone, aGender);
        }
        
        public bool IsMainAdmin(string aEmail) {
            return base.Channel.IsMainAdmin(aEmail);
        }
        
        public AspAppClient.ServiceReference1.Admin GetAdminByEmail(string aEmail) {
            return base.Channel.GetAdminByEmail(aEmail);
        }
        
        public int UpdateAdmin(AspAppClient.ServiceReference1.Admin a) {
            return base.Channel.UpdateAdmin(a);
        }
        
        public int AddNewCategory(string catName, string catImage) {
            return base.Channel.AddNewCategory(catName, catImage);
        }
        
        public bool IsCategoryExist(string catName) {
            return base.Channel.IsCategoryExist(catName);
        }
        
        public int AddNewUser(string uName, string uEmail, string uGender, string uBirthday, string uPass) {
            return base.Channel.AddNewUser(uName, uEmail, uGender, uBirthday, uPass);
        }
        
        public bool CheckUserExist(string uEmail, string uPass) {
            return base.Channel.CheckUserExist(uEmail, uPass);
        }
    }
}
