//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfAppClientAdmin.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Admin", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class Admin : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdminEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdminGenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdminNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdminPasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdminPhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsMainAdminField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdminEmail {
            get {
                return this.AdminEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.AdminEmailField, value) != true)) {
                    this.AdminEmailField = value;
                    this.RaisePropertyChanged("AdminEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdminGender {
            get {
                return this.AdminGenderField;
            }
            set {
                if ((object.ReferenceEquals(this.AdminGenderField, value) != true)) {
                    this.AdminGenderField = value;
                    this.RaisePropertyChanged("AdminGender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdminName {
            get {
                return this.AdminNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AdminNameField, value) != true)) {
                    this.AdminNameField = value;
                    this.RaisePropertyChanged("AdminName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdminPassword {
            get {
                return this.AdminPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.AdminPasswordField, value) != true)) {
                    this.AdminPasswordField = value;
                    this.RaisePropertyChanged("AdminPassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdminPhone {
            get {
                return this.AdminPhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.AdminPhoneField, value) != true)) {
                    this.AdminPhoneField = value;
                    this.RaisePropertyChanged("AdminPhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsMainAdmin {
            get {
                return this.IsMainAdminField;
            }
            set {
                if ((this.IsMainAdminField.Equals(value) != true)) {
                    this.IsMainAdminField = value;
                    this.RaisePropertyChanged("IsMainAdmin");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Category", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class Category : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CategoryImage {
            get {
                return this.CategoryImageField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryImageField, value) != true)) {
                    this.CategoryImageField = value;
                    this.RaisePropertyChanged("CategoryImage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CategoryName {
            get {
                return this.CategoryNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryNameField, value) != true)) {
                    this.CategoryNameField = value;
                    this.RaisePropertyChanged("CategoryName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class Product : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StockField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryField, value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductId {
            get {
                return this.ProductIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductIdField, value) != true)) {
                    this.ProductIdField = value;
                    this.RaisePropertyChanged("ProductId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductImage {
            get {
                return this.ProductImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductImageField, value) != true)) {
                    this.ProductImageField = value;
                    this.RaisePropertyChanged("ProductImage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductName {
            get {
                return this.ProductNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductNameField, value) != true)) {
                    this.ProductNameField = value;
                    this.RaisePropertyChanged("ProductName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Stock {
            get {
                return this.StockField;
            }
            set {
                if ((this.StockField.Equals(value) != true)) {
                    this.StockField = value;
                    this.RaisePropertyChanged("Stock");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPath", ReplyAction="http://tempuri.org/IService1/GetPathResponse")]
        string GetPath();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPath", ReplyAction="http://tempuri.org/IService1/GetPathResponse")]
        System.Threading.Tasks.Task<string> GetPathAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CheckAdminExist", ReplyAction="http://tempuri.org/IService1/CheckAdminExistResponse")]
        bool CheckAdminExist(string aEmail, string aPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CheckAdminExist", ReplyAction="http://tempuri.org/IService1/CheckAdminExistResponse")]
        System.Threading.Tasks.Task<bool> CheckAdminExistAsync(string aEmail, string aPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddNewAdmin", ReplyAction="http://tempuri.org/IService1/AddNewAdminResponse")]
        int AddNewAdmin(string aName, string aEmail, string aPass, string aPhone, string aGender);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddNewAdmin", ReplyAction="http://tempuri.org/IService1/AddNewAdminResponse")]
        System.Threading.Tasks.Task<int> AddNewAdminAsync(string aName, string aEmail, string aPass, string aPhone, string aGender);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/IsMainAdmin", ReplyAction="http://tempuri.org/IService1/IsMainAdminResponse")]
        bool IsMainAdmin(string aEmail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/IsMainAdmin", ReplyAction="http://tempuri.org/IService1/IsMainAdminResponse")]
        System.Threading.Tasks.Task<bool> IsMainAdminAsync(string aEmail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAdminByEmail", ReplyAction="http://tempuri.org/IService1/GetAdminByEmailResponse")]
        WpfAppClientAdmin.ServiceReference1.Admin GetAdminByEmail(string aEmail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAdminByEmail", ReplyAction="http://tempuri.org/IService1/GetAdminByEmailResponse")]
        System.Threading.Tasks.Task<WpfAppClientAdmin.ServiceReference1.Admin> GetAdminByEmailAsync(string aEmail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateAdmin", ReplyAction="http://tempuri.org/IService1/UpdateAdminResponse")]
        int UpdateAdmin(WpfAppClientAdmin.ServiceReference1.Admin a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateAdmin", ReplyAction="http://tempuri.org/IService1/UpdateAdminResponse")]
        System.Threading.Tasks.Task<int> UpdateAdminAsync(WpfAppClientAdmin.ServiceReference1.Admin a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteAdmin", ReplyAction="http://tempuri.org/IService1/DeleteAdminResponse")]
        int DeleteAdmin(string em);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteAdmin", ReplyAction="http://tempuri.org/IService1/DeleteAdminResponse")]
        System.Threading.Tasks.Task<int> DeleteAdminAsync(string em);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddNewCategory", ReplyAction="http://tempuri.org/IService1/AddNewCategoryResponse")]
        int AddNewCategory(string catName, string catImage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddNewCategory", ReplyAction="http://tempuri.org/IService1/AddNewCategoryResponse")]
        System.Threading.Tasks.Task<int> AddNewCategoryAsync(string catName, string catImage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/IsCategoryExist", ReplyAction="http://tempuri.org/IService1/IsCategoryExistResponse")]
        bool IsCategoryExist(string catName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/IsCategoryExist", ReplyAction="http://tempuri.org/IService1/IsCategoryExistResponse")]
        System.Threading.Tasks.Task<bool> IsCategoryExistAsync(string catName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectAllCategoryList", ReplyAction="http://tempuri.org/IService1/SelectAllCategoryListResponse")]
        WpfAppClientAdmin.ServiceReference1.Category[] SelectAllCategoryList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectAllCategoryList", ReplyAction="http://tempuri.org/IService1/SelectAllCategoryListResponse")]
        System.Threading.Tasks.Task<WpfAppClientAdmin.ServiceReference1.Category[]> SelectAllCategoryListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddNewProduct", ReplyAction="http://tempuri.org/IService1/AddNewProductResponse")]
        int AddNewProduct(WpfAppClientAdmin.ServiceReference1.Product p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddNewProduct", ReplyAction="http://tempuri.org/IService1/AddNewProductResponse")]
        System.Threading.Tasks.Task<int> AddNewProductAsync(WpfAppClientAdmin.ServiceReference1.Product p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteProduct", ReplyAction="http://tempuri.org/IService1/DeleteProductResponse")]
        int DeleteProduct(string productid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteProduct", ReplyAction="http://tempuri.org/IService1/DeleteProductResponse")]
        System.Threading.Tasks.Task<int> DeleteProductAsync(string productid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/IsProductExist", ReplyAction="http://tempuri.org/IService1/IsProductExistResponse")]
        bool IsProductExist(string productid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/IsProductExist", ReplyAction="http://tempuri.org/IService1/IsProductExistResponse")]
        System.Threading.Tasks.Task<bool> IsProductExistAsync(string productid);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WpfAppClientAdmin.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WpfAppClientAdmin.ServiceReference1.IService1>, WpfAppClientAdmin.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetPath() {
            return base.Channel.GetPath();
        }
        
        public System.Threading.Tasks.Task<string> GetPathAsync() {
            return base.Channel.GetPathAsync();
        }
        
        public bool CheckAdminExist(string aEmail, string aPassword) {
            return base.Channel.CheckAdminExist(aEmail, aPassword);
        }
        
        public System.Threading.Tasks.Task<bool> CheckAdminExistAsync(string aEmail, string aPassword) {
            return base.Channel.CheckAdminExistAsync(aEmail, aPassword);
        }
        
        public int AddNewAdmin(string aName, string aEmail, string aPass, string aPhone, string aGender) {
            return base.Channel.AddNewAdmin(aName, aEmail, aPass, aPhone, aGender);
        }
        
        public System.Threading.Tasks.Task<int> AddNewAdminAsync(string aName, string aEmail, string aPass, string aPhone, string aGender) {
            return base.Channel.AddNewAdminAsync(aName, aEmail, aPass, aPhone, aGender);
        }
        
        public bool IsMainAdmin(string aEmail) {
            return base.Channel.IsMainAdmin(aEmail);
        }
        
        public System.Threading.Tasks.Task<bool> IsMainAdminAsync(string aEmail) {
            return base.Channel.IsMainAdminAsync(aEmail);
        }
        
        public WpfAppClientAdmin.ServiceReference1.Admin GetAdminByEmail(string aEmail) {
            return base.Channel.GetAdminByEmail(aEmail);
        }
        
        public System.Threading.Tasks.Task<WpfAppClientAdmin.ServiceReference1.Admin> GetAdminByEmailAsync(string aEmail) {
            return base.Channel.GetAdminByEmailAsync(aEmail);
        }
        
        public int UpdateAdmin(WpfAppClientAdmin.ServiceReference1.Admin a) {
            return base.Channel.UpdateAdmin(a);
        }
        
        public System.Threading.Tasks.Task<int> UpdateAdminAsync(WpfAppClientAdmin.ServiceReference1.Admin a) {
            return base.Channel.UpdateAdminAsync(a);
        }
        
        public int DeleteAdmin(string em) {
            return base.Channel.DeleteAdmin(em);
        }
        
        public System.Threading.Tasks.Task<int> DeleteAdminAsync(string em) {
            return base.Channel.DeleteAdminAsync(em);
        }
        
        public int AddNewCategory(string catName, string catImage) {
            return base.Channel.AddNewCategory(catName, catImage);
        }
        
        public System.Threading.Tasks.Task<int> AddNewCategoryAsync(string catName, string catImage) {
            return base.Channel.AddNewCategoryAsync(catName, catImage);
        }
        
        public bool IsCategoryExist(string catName) {
            return base.Channel.IsCategoryExist(catName);
        }
        
        public System.Threading.Tasks.Task<bool> IsCategoryExistAsync(string catName) {
            return base.Channel.IsCategoryExistAsync(catName);
        }
        
        public WpfAppClientAdmin.ServiceReference1.Category[] SelectAllCategoryList() {
            return base.Channel.SelectAllCategoryList();
        }
        
        public System.Threading.Tasks.Task<WpfAppClientAdmin.ServiceReference1.Category[]> SelectAllCategoryListAsync() {
            return base.Channel.SelectAllCategoryListAsync();
        }
        
        public int AddNewProduct(WpfAppClientAdmin.ServiceReference1.Product p) {
            return base.Channel.AddNewProduct(p);
        }
        
        public System.Threading.Tasks.Task<int> AddNewProductAsync(WpfAppClientAdmin.ServiceReference1.Product p) {
            return base.Channel.AddNewProductAsync(p);
        }
        
        public int DeleteProduct(string productid) {
            return base.Channel.DeleteProduct(productid);
        }
        
        public System.Threading.Tasks.Task<int> DeleteProductAsync(string productid) {
            return base.Channel.DeleteProductAsync(productid);
        }
        
        public bool IsProductExist(string productid) {
            return base.Channel.IsProductExist(productid);
        }
        
        public System.Threading.Tasks.Task<bool> IsProductExistAsync(string productid) {
            return base.Channel.IsProductExistAsync(productid);
        }
    }
}
